## Import Required Libries

In [1]:
import numpy as np
import pandas as pd
import os
import joblib
import warnings
warnings.filterwarnings("ignore")

## Import DataSet

In [2]:
data = pd.read_csv('../Data.csv')

## Extract Information about DataSet

In [3]:
data.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP,image_url
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135,https://source.unsplash.com/600x400/?BMW+1+Ser...
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650,https://source.unsplash.com/600x400/?BMW+1+Ser...
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350,https://source.unsplash.com/600x400/?BMW+1+Ser...
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450,https://source.unsplash.com/600x400/?BMW+1+Ser...
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500,https://source.unsplash.com/600x400/?BMW+1+Ser...

In [4]:
data.shape

(11914, 17)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11914 non-null  object
 1   Model              11914 non-null  object
 2   Year               11914 non-null  int64
 3   Engine Fuel Type   11911 non-null  object
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object
 7   Driven_Wheels      11914 non-null  object
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object
 10  Vehicle Size       11914 non-null  object
 11  Vehicle Style      11914 non-null  object
 12  highway MPG        11914 non-null  int64
 13  city mpg           11914 non-null  int64
 14  Popularity         11914 non-null  int64
 15  MSRP               11914 non-null  int64
 16  image_url          11914 non-null  object
dtypes: float64(3), int64(5), object(9)
memory usage: 1.5+ MB

In [6]:
data.describe()

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
count,11914.000000,11845.00000,11884.000000,11908.000000,11914.000000,11914.000000,11914.000000,1.191400e+04
mean,2010.384338,249.38607,5.628829,3.436093,26.637485,19.733255,1554.911197,4.059474e+04
std,7.579740,109.19187,1.780559,0.881315,8.863001,8.987798,1441.855347,6.010910e+04
min,1990.000000,55.00000,0.000000,2.000000,12.000000,7.000000,2.000000,2.000000e+03
25%,2007.000000,170.00000,4.000000,2.000000,22.000000,16.000000,549.000000,2.100000e+04
50%,2015.000000,227.00000,6.000000,4.000000,26.000000,18.000000,1385.000000,2.999500e+04
75%,2016.000000,300.00000,6.000000,4.000000,30.000000,22.000000,2009.000000,4.223125e+04
max,2017.000000,1001.00000,16.000000,4.000000,354.000000,137.000000,5657.000000,2.065902e+06

## Remove the Useless Columns

In [7]:
data.drop(['Number of Doors', 'image_url', 'Engine Fuel Type'], axis = 1, inplace = True)

## Put UnderScore in Column Name

In [8]:
data.columns = [col.replace(" ", "_") for col in data.columns]

## Checking Null Value

In [9]:
data.isna().sum()

Make                    0
Model                   0
Year                    0
Engine_HP              69
Engine_Cylinders       30
Transmission_Type       0
Driven_Wheels           0
Market_Category      3742
Vehicle_Size            0
Vehicle_Style           0
highway_MPG             0
city_mpg                0
Popularity              0
MSRP                    0
dtype: int64

## Handling Null Values

In [10]:
for i in data.columns:
    if data[i].dtype == 'object':
        data[i] = data[i].fillna(data[i].mode()[0])
    else:
        data[i] = data[i].fillna(data[i].mean())

In [11]:
data.isna().sum()

Make                 0
Model                0
Year                 0
Engine_HP            0
Engine_Cylinders     0
Transmission_Type    0
Driven_Wheels        0
Market_Category      0
Vehicle_Size         0
Vehicle_Style        0
highway_MPG          0
city_mpg             0
Popularity           0
MSRP                 0
dtype: int64

## Seprate Independent and Dependent Variable from the DataSet

In [12]:
X = data.drop('MSRP', axis = 1)
y = data['MSRP']

## Label Encoder

In [13]:
from sklearn.preprocessing import LabelEncoder
import joblib
os.makedirs('Encoder/Prediction', exist_ok=True)
for i in X.columns:
    if X[i].dtype == 'object':
        le = LabelEncoder()
        X[i] = le.fit_transform(X[i])
        joblib.dump(le, f'Encoder/Prediction/{i}_Encoder.pkl')
        print(f'Encoder {i}_Encoder.pkl Saved Successfully')

Encoder Make_Encoder.pkl Saved Successfully
Encoder Model_Encoder.pkl Saved Successfully
Encoder Transmission_Type_Encoder.pkl Saved Successfully
Encoder Driven_Wheels_Encoder.pkl Saved Successfully
Encoder Market_Category_Encoder.pkl Saved Successfully
Encoder Vehicle_Size_Encoder.pkl Saved Successfully
Encoder Vehicle_Style_Encoder.pkl Saved Successfully

## Split Training and Testing DataSet

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

## Applying this Model

In [15]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators = 100, random_state = 42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

## Model Testing

In [16]:
y_pred = model.predict(X_test)

## Checking the Model Accuracy

In [17]:
from sklearn.metrics import r2_score
acc = r2_score(y_test, y_pred)
print('Accuracy of the is ',round((acc*100),2))

Accuracy of the is  98.03

## Saving the Model

In [18]:
os.makedirs('../Models', exist_ok=True)
joblib.dump(model, 'Models/Prediction.pkl')
print('Model Saved Successfully')

Model Saved Successfully